### ISSUE TITLE
'View All' menu navigation issue

### ISSUE THREAD

**Issue by anthonysimone** [pattern-lab/patternlab-php#370] opened 2016-08-12 13:37 UTC
I just updated patten lab core this morning and noticed the 'View All' items in the navigation were behaving a bit oddly. The 'View All' item on the top level categories (Molecules, Organisms, etc) seems instead to redirect to the last item in the previous menu. So for example, clicking on Organisms -> View All redirects to the last item in the Molecules first level dropdown. However, if you click the same View All link a second time before navigating away from the page, then it does bring you to the All page as expected. I created a new project and tested it in a fresh environment to make sure I didn't just mess up my own project, but I saw the same behavior there as well.

**Comment by hctom** [comment] 2016-08-18 08:34
I can confirm this behavior on our side.

**Comment by hctom** [comment] 2016-08-18 08:53
This issue may be closed, due to the issue filed again at https://github.com/pattern-lab/styleguidekit-assets-default/issues/41 as this repository handles all the URL navigation stuff as far as I see.

**Comment by EvanLovely** [comment] 2017-10-12 23:21
All fixed now as of v2.8.0!!

**Closed as completed by EvanLovely** 2017-10-12 23:21 UTC
