### ISSUE TITLE
Override _data.json in template

### ISSUE THREAD

**Issue by CharlJKruger** [pattern-lab/patternlab-php#268] opened 2015-02-09 12:10 UTC
Hi and thanks for an awesome project.

Im having an issue where i cant seem to override some data:

I have the following molecule ( 00-progress-bar.mustache ):

`<div class="progress {{ progress-bar.bg-color }}">`
`    <div class="progress-bar {{ progress-bar.color }}" role="progressbar" aria-valuenow="{{ percent }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress-bar.percent }}%;">`
`      <span class="sr-only">{{ progress-bar.percent }}% Complete</span>`
`    </div>`
`</div>`

with the following set in _data.json:

`{`
`    "progress-bar" : {`
`        "percent": "90",`
`        "bg-color": "",`
`        "color": ""`
`    }`
`}`

This renders perfect on the molecule though when trying to override the data in template ( e.g. 00-basic-template.mustache ), I get no result - the molucule just uses the _data.json and not the data set in, e.g. 00-basic-template.json

In the example above, my 00-basic-template.json looks like:

`{`
`    "progress-bar" : {`
`        "percent": "90",`
`        "bg-color": "",`
`        "color": ""`
`    }`
}`

It what im trying to do possible?

Also, say I had included `{{> molecules-progress-bar }}` twice within 00-basic-template.mustache and I wanted the bg-color to differ, how would I pass 2 different bg colors to the seperate `{{> molecules-progress-bar }}` ?

Thanks again.

**Comment by dmolsen** [comment] 2015-02-09 17:41
@CharlJKruger -

A quick test worked for me so I'm not sure what's going on. I did note that your example data in `_data.json` is exactly the same as `00-basic-template.json`. Maybe that's the cause?

To pass different colors you're going to have to use [pattern parameters](http://patternlab.io/docs/pattern-parameters.html).

**Comment by TxHawks** [comment] 2015-02-09 18:55
Another way to pass different colors, is to wrap your includes with a section block, so that your mustache file looks like this:
````
{{# section }}
  {{> molecules-progress-bar }}
{{/ section }}
````
And your `00-basic-template.json`:
````
{
  "section": [
    {
      "progress-bar" : {
        "percent": "90",
        "bg-color": "#fff",
        "color": "#000"
      }
    },
    {
      "progress-bar" : {
        "percent": "60",
        "bg-color": "#000",
        "color": "#fff"
      }
    }
  ]
}
````
`#section` is an array with two node, which means the `progress-bar` molecule will be rendered two times, once with the values of the first node and then with the values of the second node. This should also override the values in `_data.json` (though, as @dmolsen mentioned, they should have also been overridden by the example you provided).

**Comment by dmolsen** [comment] 2015-02-09 18:56
I have to remember that trick, @TxHawks . Nice :)

**Comment by TxHawks** [comment] 2015-02-09 19:01
Happy to be of service.

**Comment by CharlJKruger** [comment] 2015-02-09 19:18
@TxHawks that's exactly what I was trying to do, thanks to all. Will also use the pattern parameters for some testing and so forth.

**Comment by TxHawks** [comment] 2015-02-10 06:34
@CharlJKruger just keep in mind that while pattern parameters can be very helpful, they are not real mustache, and cannot be overridden by json files

**Comment by dmolsen** [comment] 2015-02-24 02:18
Since this was answered I'm closing it up.

**Closed by dmolsen** 2015-02-24 02:18 UTC
