### ISSUE TITLE
Linking to Patterns with Pattern Lab's Default link Variable via Json

### ISSUE THREAD

**Issue by guideveloper** [pattern-lab/patternlab-php#303] opened 2015-06-04 11:03 UTC
Hey guys,

So I really need to use the Linking to Patterns with Pattern Lab's Default link Variable but via my json so that i can dynamically change a links url on a page to page basis.

I have tried setting my mustache template like so:
```
{{#subCategories}}
<li><a href="{{ uri }}">{{name}}</a></li>
{{/subCategories}}
```
and my json like so:
```
"subCategories":[  
	         {  
	            "id":"47",
	            "name":"Books",
	            "uri":"link.pages-entertainment"
	         },
```

This seems to link.pages-entertainment as a string in the irl and doesnt convert the url to the correct path.

any ideas are very welcome on this.

thanks
@GUIDeveloper

**Comment by bradfrost** [comment] 2015-06-07 22:14
Hi @guideveloper,
The following code should work:

`"url" : "link.pages-entertainment"`

Looking at your example, it doesn't look like there's anything wrong with how you've structured it. But try changed it to `url` instead of `uri`. I think @dmolsen may have hard-coded it to link up to `url`.

**Comment by guideveloper** [comment] 2015-06-08 08:12
Nice one @bradfrost but this seems to just output the tag in the href instead of converting it to the actual link?
```
<a href="link.pages-visited-retailers">Visited retailers</a>
```
Do you think this could be to do with that I'm using the php version?

thanks

@GUIDeveloper

**Comment by daigofuji** [comment] 2015-06-08 13:47
Try: 
```
<a href="{{ link.pages-visited-retailers }}">Visited retailers</a>
```
Maybe?

**Comment by guideveloper** [comment] 2015-06-08 13:49
Yeah this works just fine @daigofuji ,  the issue is that i am loading my links via Json into my mustache template so really need the links populating from there.

**Comment by bradfrost** [comment] 2015-06-09 00:17
@guideveloper try downloading a clean version of Pattern Lab and seeing if that works. Don't think I have any other ideas for you.

**Comment by guideveloper** [comment] 2015-06-10 09:21
Ok mate cheers I'll give that a go 

thanks

@bradfrost and @daigofuji

**Comment by Founts** [comment] 2015-06-18 20:36
@guideveloper I encountered the same issue just now for what it's worth. Was working fine then a new entry into my json file had the function that creates links start bombing out. The only difference I can find is the url is burried three levels deep in my json vs two levels.
```
"news" : [
		{
			"widget-entry" : [
				{ 
					"url" : "link.pages-publications",
```
Is your snippet of code above two levels deep or deeper?

**Comment by guideveloper** [comment] 2015-06-19 07:40
@Founts yeah mine is also three levels deep
```
"myAccountMenuItems":[
		{  
	      "id":"458",
	      "name":"My stuff",
	      "uri":"my-stuff",
	      "subCategories":[  
	         {  
	            "id":"9017",
	            "name":"Favourite retailers",
	            "url":"link.pages-posters-flyers"
	         },
```

**Comment by guideveloper** [comment] 2015-06-25 15:35
@Founts Don't suppose you found a fix for this did you?

**Comment by Founts** [comment] 2015-06-25 18:23
@guideveloper nope. Thought about restructuring my code somehow but had other pressing items to tackle.

**Comment by Stalski** [comment] 2015-12-07 19:05
Same problem here. 
The problem is that PatternLab suggests to use Pages as specific version of a Template. So this way you can include the partial template and give your site specific content via the JSON file. Well not all content, because internal patternlab links are not compiled in json files. 

Every solution I can come up with throws away at least a couple advantages of PatternLab, 

This is a real blocker imo.

**Comment by dmolsen** [comment] 2015-12-07 20:28
@Stalski -

Are you on `dev`? I'm assuming so but wanted to double-check just in case I was forgetting something from `master`. The issue is the use of `array_walk_recursive()`. Have a fix but haven't fired up `dev` in ages and don't want to commit something that isn't helpful.

**Comment by Stalski** [comment] 2015-12-08 16:23
Can you post it here or by email? I would be glad to test it out.
@dmolsen

**Comment by dmolsen** [comment] 2015-12-08 17:49
The issue is because of this `array_walk_recursive()` in [DataMergeExporter](https://github.com/pattern-lab/patternlab-php/blob/713098396975a372c071e3b5af7632cdf82bf210/core/lib/PatternLab/PatternData/Exporters/DataMergeExporter.php#L49-L50). Turns out `array_walk_recursive()` doesn't go into nodes that contain arrays. Hence the depth issue.

The fix is to add the `recursiveWalk()` and `compareReplaceListVars()` functions to your `Data.php` class [from PL core](https://github.com/pattern-lab/patternlab-php-core/blob/58fb7954bb8449d7d459213817e13e65217fb359/src/PatternLab/Data.php#L35-L68). Make the `recursiveWalk()` function public. Then replace the `array_walk_recursive()` call above with:

```php
Data::$store = Data::recursiveWalk(Data::$store);
```

That should work since `Data::$store` is public in the version of PL you're using.

**Comment by Stalski** [comment] 2015-12-10 21:28
I was able to set it up (dev branch I mean)
It did not work by default, but after I saw in code that the folders were changed (cfr _meta , _annotations, ...) , and after fixing some bugs as well like arrays not being arrays , stuff like that.  If you want more info or a patch, let me know.
Also a problem then with the autoloader SPL classes which were not there but I commented this out for the moment. 

After that it worked, and it is much more verbose, E.G. "this is preserved word" or "you probably made a typo in ..." . Nice features :)

I will now take a look at the piece of code you mentioned. Can you just give me the example on how the json should be defined? I mean, suppose the json variable is "link-url" : "link.page-one" or more like "link-url" : "{{link.page-one}} or some other method? In other words, what is the code expecting to find in the json?
thx in advance

**Comment by dmolsen** [comment] 2015-12-10 21:35
Wow. Like I said I haven't been in there in a while so glad you were able to work through the problems :) Let's say this was a snippet from your mustache file and you wanted to link to the `pages-homepage` pattern:

```
<a href="{{ homelink }}">Home</a>
```

Then the JSON would be:

```
"homelink": "link.pages-homepage"
```

Make sense?

**Comment by Stalski** [comment] 2015-12-10 21:57
Hi, 

it needed the getOptions method as well  btw ;) 
So The string are correctly replaced, thx for the help! But still one small problem, the pages are not rendered anymore like they were in the master branch. 

I now get : The requested URL /05-pages-01-content-overview-05-news-archive/05-pages-01-content-overview-05-news-archive.html was not found on this server. 

So I am investigating this for now. If you have any quick idea's , it would be helpful. I think the root app url is not correct or something.

**Comment by Stalski** [comment] 2015-12-11 14:15
This is really strange. I don't seem to find where the actual store is built with the correct URL (not path) to the patterns. 
I know it does not take /patterns/ into account in the url, so I know what the replacement should have done, but I don't seem to find the correct way to fix the "base uri" 

I tried to set the "patternPublicDir" in the config.ini but that did not do the trick. 

Are there any changes that I am not aware of in the dev branch?

**Comment by Stalski** [comment] 2015-12-11 14:30
Nevermind ;) Found it

It needed a change in "DataLinkExporter":
    Data::$store["link"][$patternStoreKey] = "../../patterns/".$patternStoreData["pathDash"]."/".$patternStoreData["pathDash"].".html";
instead of 
    Data::$store["link"][$patternStoreKey] = "../../".$patternStoreData["pathDash"]."/".$patternStoreData["pathDash"].".html";

Win! I am really looking forward to the new version (with yaml as in your commit)

**Comment by Stalski** [comment] 2015-12-11 15:15
I don't know if this will be useful but I'll add the patch in a zip here. 
If you want me take appropriate action with a pull request, let me know. We are using this extensively for a big client, so it is very important for us to have this functionality into the stable release. 
So If you need me, just call out to me.

[patternlab-php-dev.patch.zip](https://github.com/pattern-lab/patternlab-php/files/59530/patternlab-php-dev.patch.zip)

**Comment by dmolsen** [comment] 2015-12-11 15:24
FWIW, I'm probably not going to merge anything here to `master` because I believe most of that stuff is addressed in the true development edition of PL. Down to our last big feature to implement. It's still not stable but you can [preview the development edition](https://github.com/pattern-lab/edition-php-development) if you want.

Thanks again for getting that to work.

**Comment by Stalski** [comment] 2016-04-04 12:33
So basically at this time, there is no stable version yet where internal linking from a json file can be achieved? 
I am not a fan of using the development edition which is not stable for a real project in production. 
Can you give me some pointers on how I show see this? What to use for a project in production with the possibility to have internal linking?

**Closed** 2016-07-13 14:53 UTC
Labels: wontfix
